lighter:
    max-running-jobs: 5
    spark-history-server-url: http://localhost/spark-history/
    frontend-path: file:${FRONTEND_PATH:../frontend/build}
    py-gateway-port: 25333
    url: http://lighter.spark:8080
    session:
        timeout-minutes: 90
        permanent-sessions: []
    kubernetes:
        enabled: true
        master: k8s://kubernetes.default.svc.cluster.local:443
        namespace: spark
        service-account: spark
        container-image: "218320193259.dkr.ecr.eu-central-1.amazonaws.com/hellcat:0.0.2796"
        max-log-size: 500
        submit-props:
          "spark.kubernetes.container.image": ${lighter.kubernetes.container-image}
          "spark.kubernetes.namespace": ${lighter.kubernetes.namespace}
          "spark.kubernetes.authenticate.driver.serviceAccountName": ${lighter.kubernetes.service-account}
          "spark.kubernetes.driver.podTemplateFile": "/home/app/k8s/driver_pod_template.yaml"
          "spark.kubernetes.executor.podTemplateFile": "/home/app/k8s/executor_pod_template.yaml"
          "spark.hadoop.fs.s3a.fast.upload": "true"
    storage:
        jdbc:
            enabled: true
            url: jdbc:h2:mem:lighter;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
            username: sa
            password: ""
            driverClassName: org.h2.Driver

# Micronaut specific configs
jackson:
    serializationInclusion: ALWAYS
    serialization:
        writeDatesAsTimestamps: false


shedlock:
    defaults:
        lock-at-most-for: 10m

flyway:
    datasources:
        default:
            enabled: true

micronaut:
    server:
        thread-selection: AUTO
        cors:
            enabled: true
    application:
        name: lighter
    router:
        static-resources:
            swagger:
                paths: classpath:META-INF/swagger
                mapping: /swagger/**
            swagger-ui:
                enabled: true
                paths: classpath:META-INF/swagger/views/swagger-ui
                mapping: /swagger-ui/**

    metrics:
        enabled: true
        export:
            prometheus:
                enabled: true
                step: PT1M
                descriptions: true
