name: Build backend & frontend
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-frontend:
    uses: exacaster/lighter/.github/workflows/build-frontend.yml@${{ github.ref_name }}
  build-java:
    uses: exacaster/lighter/.github/workflows/build-java.yml@${{ github.ref_name }}
