name: build backend and frontend
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-frontend:
    uses: ./.github/workflows/build-frontend.yml
  build-java:
    uses: ./.github/workflows/build-java.yml
