name: Build backend & frontend
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-frontend:
    uses: {owner}/{repo}/.github/workflows/build-frontend.yml@{ref}
  build-java:
    uses: {owner}/{repo}/.github/workflows/build-java.yml@{ref}
