name: Clean Github container registry
on:
  workflow_call: { }
  pull_request:
    types: [ closed ]

jobs:
  clean-registry:
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - spark_version: 3.3.3
            hadoop_version: 3
          - spark_version: 3.4.1
            hadoop_version: 3
          - spark_version: 3.5.0
            hadoop_version: 3
    steps:
      - name: Base ref
        run: |
            LOWER_BRANCH=${{ github.event.pull_request.head.ref }}
            SLUG_BRANCH=$(echo "$LOWER_BRANCH" | sed -e 's/[^a-zA-Z0-9]/-/g' -e 's/--/-/g')
            echo "BASE_REF=$SLUG_BRANCH" >> $GITHUB_ENV
      - name: Delete tag on PR close or merge
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IMAGE_NAME: ${{ github.repository }}
          BASE_REF: ${{ env.BASE_REF }}
        run: |
          TAG_TO_DELETE=${IMAGE_NAME}:${BASE_REF}-spark${{ matrix.spark_version }}
          TOKEN=$(echo "${TOKEN}" | awk '{print substr($0, 12)}')
          curl -X DELETE -H "Authorization: token ${TOKEN}" -H "Accept: application/vnd.github.v3+json" "https://ghcr.io/v2/${IMAGE_NAME}/manifests/${TAG_TO_DELETE}"