name: Publish image to Github container registry
on:
  workflow_call: { }
env:
  TARGET_PLATFORMS: linux/amd64,linux/arm64
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish-registry:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - spark_version: 3.4.2
            hadoop_version: 3
          - spark_version: 3.5.1
            hadoop_version: 3
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          build-args: |
            SPARK_VERSION=${{ matrix.spark_version }}
            HADOOP_VERSION=${{ matrix.hadoop_version }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/lighter_spark_${{ matrix.spark_version }}:${{ github.event.release.tag_name }}
          platforms: ${{ env.TARGET_PLATFORMS }}
