name: publish docker image
on:
  release:
    types:
      - released

jobs:
  build-frontend:
    uses: ./.github/workflows/build-frontend.yml
  build-java:
    uses: ./.github/workflows/build-java.yml
  publish-registry:
    uses: ./.github/workflows/publish-registry.yml
    needs: [ build-frontend, build-java ]
