name: Build everything & publish images
on:
  release:
    types:
      - released

jobs:
  build-frontend:
    uses: {owner}/{repo}/.github/workflows/build-frontend.yml@master
  build-java:
    uses: {owner}/{repo}/.github/workflows/build-java.yml@master
  publish-registry:
    uses: {owner}/{repo}/.github/workflows/publish-registry.yml@master
    needs: [ build-frontend, build-java ]
